language: csharp
solution: Mundialito.sln
install:
  - nuget restore Mundialito.sln
  - nuget install NUnit.Runners -Version 3.4.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Mundialito.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.0/tools/nunit3-console.exe ./Mundialito.Tests/bin/Release/Mundialito.Tests.dll
